### ISSUE TITLE
githubの使い方がわからない

### ISSUE THREAD

**Issue by jpfaw** [jpfaw/BlockInterference#2]
深刻

**Comment by natmark** [comment]
https://www.amazon.co.jp/GitHub%E5%AE%9F%E8%B7%B5%E5%85%A5%E9%96%80-~Pull-Request%E3%81%AB%E3%82%88%E3%82%8B%E9%96%8B%E7%99%BA%E3%81%AE%E5%A4%89%E9%9D%A9-PRESS-plus/dp/477416366X

**Comment by jpfaw** [comment]
基本的なことはできるようになった
