### ISSUE TITLE
ゲーム画面からの遷移時にデータの変更ができない

### ISSUE THREAD

**Issue by jpfaw** [jpfaw/BlockInterference#4]
タイトルに戻る時はstoryboardにボタン置いてるだけだし実装がクソなだけ。なんかこうクニャッとDelegate実装したら良いらしいけどよくわからない。これ解決しないとresult画面にも行けないのでいずれぶち当たる問題

**Comment by natmark** [comment]
http://www.sirochro.com/note/swift-delegate-paturn/

**Comment by jpfaw** [comment]
Delegate実装(してもらった)
